// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZwlV_UM_BJgUexpYLPIP-9txQrl-SCTg',
    appId: '1:570232457456:web:4c68fa38743e4ef00d1a35',
    messagingSenderId: '570232457456',
    projectId: 'movies-app-bcd00',
    authDomain: 'movies-app-bcd00.firebaseapp.com',
    storageBucket: 'movies-app-bcd00.firebasestorage.app',
    measurementId: 'G-V34FP1VK02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNxYIJG8b17rt7STmRZ63fdTdxLu6UEo',
    appId: '1:570232457456:android:d152f23cfc5527170d1a35',
    messagingSenderId: '570232457456',
    projectId: 'movies-app-bcd00',
    storageBucket: 'movies-app-bcd00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4XQhUTQgBMvSLvshc6p5qwfIaj18c_k',
    appId: '1:570232457456:ios:2ff39d9f270a7c590d1a35',
    messagingSenderId: '570232457456',
    projectId: 'movies-app-bcd00',
    storageBucket: 'movies-app-bcd00.firebasestorage.app',
    iosBundleId: 'com.moviesapp.moviesApp',
  );
}
